---
apiVersion: v1
kind: Service
metadata:
  labesl:
    app: adminer
  name: adminer
spec:
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: whoami
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: adminer
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  strategy: {}
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - image: adminer:4.7.6
        name: adminer
        ports:
        - name: http
          containerPort: 8080
        resources: {}
status: {}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: adminer
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: adminer.zasdaym.lab
    http:
      paths:
      - path: /
        backend:
          serviceName: adminer
          servicePort: 80
